common/models/Post.php
<?php

namespace common\models;


use common\models\helpers\traits\TraitUploadFile;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $title
 * @property string $image_file
 * @property string|null $description
 * @property string|null $big_description
 * @property int $user_id
 * @property int $tag_id
 * @property int $status
 * @property int $is_deleted
 * @property int $created_at
 * @property int $updated_at
 * @property int $created_by
 * @property int $updated_by
 * @property int $views
 *
 * @property Tag $tag
 * @property User $user
 */
class Post extends \yii\db\ActiveRecord
{

    use  TraitUploadFile;

    const PATH_PHOTO = '/uploads/photos/post';
    const PATH_FILE = 'post_';

    public $imageFile;
    /**
     * @var mixed|null
     */
    public $like_count = 0;

    public $dislike_count = 0;


    public function behaviors()
    {
        return [
            TimestampBehavior::class,
            BlameableBehavior::class,

        ];
    }
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'image_file', 'user_id', 'tag_id','big_description', ], 'required'],
            [['user_id', 'tag_id', 'status', 'is_deleted', 'created_at', 'updated_at', 'created_by', 'updated_by','views'], 'integer'],
            [['title', 'image_file', 'description'], 'string', 'max' => 255],
            [['created_at'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['user_id' => 'id']],
            [['tag_id'], 'exist', 'skipOnError' => true, 'targetClass' => Tag::class, 'targetAttribute' => ['tag_id' => 'id']],
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg'],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'image_file' => 'Image File',
            'description' => 'Description',
            'big_description' => 'Big Description',
            'user_id' => 'User ID',
            'tag_id' => 'Tag ID',
            'status' => 'Status',
            'is_deleted' => 'Is Deleted',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * Gets query for [[Tag]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTag()
    {
        return $this->hasOne(Tag::class, ['id' => 'tag_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }
}

backend/controllers/PostController.php
<?php

namespace backend\controllers;

use common\models\Post;
use common\models\search\PostSearch;
use Yii;
use yii\base\Response;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Post models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
                if ($model->imageFile) {
                    $model->uploadPhoto();
                }
                $model->user_id = \Yii::$app->user->id;
                $model->save(false);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }


    /**
     * Updates an existing Services model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate(int $id): Response|string
    {
        $model = $this->findModel($id);
        if ($this->request->isPost) {
            if ($model->load($this->request->post() )) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
                if ($model->image_file == null && $model->imageFile != null){
                    $model->uploadPhoto();
                }elseif ($model->imageFile != null){
                    $model->updatePhoto();
                }
                $model->save(false);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }



/**
     * Increments the like count for a specific Post model.
     * @param int $id ID of the Post
     * @return array Response data
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionLike($id)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $post = $this->findModel($id);

        if ($post) {
            $post->like_count += 1;
            $post->save(false);
            return ['success' => true, 'like_count' => $post->like_count];
        }

        return ['success' => false];
    }

    /**
     * Increments the dislike count for a specific Post model.
     * @param int $id ID of the Post
     * @return array Response data
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDislike($id)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $post = $this->findModel($id);

        if ($post) {
            $post->dislike_count += 1;
            $post->save(false);
            return ['success' => true, 'dislike_count' => $post->dislike_count];
        }

        return ['success' => false];
    }
    public function actionIncrementView($id)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $post = Post::findOne($id);
        if ($post) {
            $post->views++;
            if ($post->save()) {
                return ['success' => true, 'views' => $post->views];
            }
        }
        return ['success' => false];
    }

}

backend/controllers/TagController.php
<?php

namespace backend\controllers;

use common\models\Tag;
use common\models\search\TagSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TagController implements the CRUD actions for Tag model.
 */
class TagController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Tag models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new TagSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tag model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tag model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Tag();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Tag model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Tag model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tag model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Tag the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tag::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/PostController.php
<?php

namespace frontend\controllers;


use common\models\Post;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class PostController extends Controller
{

    public function actionIncrementView($id): array
    {
        $post = Post::findOne($id);
        if ($post) {
            $post->views++;
            $post->save();
            return ['success' => true, 'views' => $post->views];
        } else {
            return ['success' => false];
        }
    }

    protected function findModel($id)
    {
        if (($model = Post::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

backend/views/post/_form.php
<?php

use common\models\Tag;
use kartik\editors\Codemirror;
use kartik\editors\Summernote;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use kartik\select2\Select2;
use yii\bootstrap5\ActiveForm;

/** @var yii\web\View $this */
/** @var common\models\Post $model */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?=
    $form->field($model, 'tag_id')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Tag::find()->all(), 'id', 'name'),
        'options' => ['placeholder' => 'Tagni tanlang ...', 'multiple' => false],
        'pluginOptions' => [
            'tags' => true,
            'tokenSeparators' => [',', ' '],
            'maximumInputLength' => 10
        ],
    ])->label('Tag Multiple');
    ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'description', [
        'labelOptions' => ['label' => ' Short Description ']
    ])->widget(Summernote::class, [
        'useKrajeePresets' => true,
        'pluginOptions' =>  [
            'height' => 300,
            'dialogsFade' => true,
            'toolbar' => [
                ['style1', ['style']],
                ['style2', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript']],
                ['font', ['fontname', 'fontsize', 'color', 'clear']],
                ['para', ['ul', 'ol', 'paragraph', 'height']],
                ['insert', ['link', 'picture', 'video', 'table', 'hr']],
            ],
            'fontSizes' => ['8', '9', '10', '11', '12', '13', '14', '16', '18', '20', '24', '36', '48'],
            'codemirror' => [
                'theme' => Codemirror::DEFAULT_THEME,
                'lineNumbers' => true,
                'styleActiveLine' => true,
                'matchBrackets' => true,
                'smartIndent' => true,
            ],
        ]
    ]); ?>

    <br>
    <?= $form->field($model, 'imageFile')->label('Image')->fileInput([ 'accept' => 'image/png/jpeg']) ?>
    <br>





    <?=  $form->field($model, 'big_description',
    [ 'labelOptions' => ['label' => ' Big Description ']
    ])->widget(Summernote::class, [
        'useKrajeePresets' => true,
        'pluginOptions' =>  [
            'height' => 300,
            'dialogsFade' => true,
            'toolbar' => [
                ['style1', ['style']],
                ['style2', ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript']],
                ['font', ['font name', 'fontsize', 'color', 'clear']],
                ['para', ['ul', 'ol', 'paragraph', 'height']],
                ['insert', ['link', 'picture', 'video', 'table', 'hr']],
            ],
            'fontSizes' => ['8', '9', '10', '11', '12', '13', '14', '16', '18', '20', '24', '36', '48'],
            'codemirror' => [
                'theme' => Codemirror::DEFAULT_THEME,
                'lineNumbers' => true,
                'styleActiveLine' => true,
                'matchBrackets' => true,
                'smartIndent' => true,
            ],
        ]
    ]); ?>


    <?= $form->field($model, 'status')->dropDownList([1=>'active', 0=>'inactive']) ?>

    <br>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var common\models\search\PostSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'image_file') ?>

    <?= $form->field($model, 'description') ?>
    <?= $form->field($model, 'big_description') ?>

    <?= $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'tag_id') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'is_deleted') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/post/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var common\models\Post $model */

$this->title = 'Create Post';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/post/index.php
<?php

use common\models\helpers\StatusHelpers;
use common\models\Post;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\grid\GridView;

/** @var yii\web\View $this */
/** @var common\models\search\PostSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Posts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Post', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],



            [
                'attribute' => 'user_id',
                'label'=>'Username',
                'value' => function ($model) {
                    return  $model->user->username;
                }
            ],

            [
                'attribute' => 'tag_id',
                'label'=>'Tag',
                'value' => function ($model) {
                    return  $model->tag->name;
                }
            ],

            'title',

            [
                'attribute' => 'image_file',
                'value' => function ($data) {
                    return $data->getPhotoSrc();
                },
                'format' => ['image', ['width' => 140, 'height' => 80]],
            ],
            [
                'attribute' => 'description',
                'value' => function ($data) {
                    return strip_tags($data->description);
                },
                'format' => 'text',
            ],
              'created_at:date',
            [
                'attribute' => 'big_description',
                'value' => function ($data) {
                    return strip_tags($data->big_description);
                },
                'format' => 'text',
            ],

            [
                'attribute' => 'status',
                'value'=> function (Post $model) {
                    return StatusHelpers::getStatusLabel($model->status);
                },
                'format' => 'html',
                'filter' => StatusHelpers::getStatusList()

            ],

            [
                'class' => ActionColumn::className(),
                'urlCreator' => function ($action, Post $model, $key, $index, $column) {
                    return Url::toRoute([$action, 'id' => $model->id]);
                 }
            ],
        ],
    ]); ?>


</div>

backend/views/post/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var common\models\Post $model */

$this->title = 'Update Post: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="post-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/post/view.php
<?php

use common\models\helpers\StatusHelpers;
use common\models\Post;
use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var common\models\Post $model */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="post-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [

            [
                'attribute' => 'image_file',
                'label'=>'Image',
                'value' => function ($data) {
                    return $data->getPhotoSrc();
                },
                'format' => ['image', ['width' => 140, 'height' => 80]]
            ],
            'title',
            [
                'attribute' => 'description',
                'value' => function ($data) {
                    return strip_tags($data->description);
                },
                'format' => 'text',
            ],
            [
                'attribute' => 'big_description',
                'value' => function ($data) {
                    return strip_tags($data->big_description);
                },
                'format' => 'text',
            ],

//            [
//                'format' => 'html',
//                'attribute' => 'user_id',
//                'value' => ($model->user ?
//                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['user/index']).' '.
//                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->user->name, ['user/view', 'id' => $model->user->id,]).' '.
//                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Chap'=>['user_id' => $model->name]])
//                    :
//                    '<span class="label label-warning">?</span>'),
//            ],
            [
                'format' => 'html',
                'attribute' => 'tag_id',
                'value' => ($model->tag ?
                    Html::a('<i class="glyphicon glyphicon-list"></i>', ['tag/index']).' '.
                    Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->tag->name, ['tag/view', 'id' => $model->tag->id,]).' '.
                    Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Chap'=>['tag_id' => $model->tag_id]])
                    :
                    '<span class="label label-warning">?</span>'),
            ],
            [
                'attribute' => 'status',
                'value'=> function (Post $model) {
                    return StatusHelpers::getStatusLabel($model->status);
                },
                'format' => 'html',


            ],


        ],
    ]) ?>

</div>