backend/controllers/PostController.php
<?php

namespace backend\controllers;

use common\models\Post;
use common\models\search\PostSearch;
use Yii;
use yii\base\Response;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Post models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Post model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Post();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
                if ($model->imageFile) {
                    $model->uploadPhoto();
                }
                $model->user_id = \Yii::$app->user->id;
                $model->save(false);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }


    /**
     * Updates an existing Services model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate(int $id): Response|string
    {
        $model = $this->findModel($id);
        if ($this->request->isPost) {
            if ($model->load($this->request->post() )) {
                $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
                if ($model->image_file == null && $model->imageFile != null){
                    $model->uploadPhoto();
                }elseif ($model->imageFile != null){
                    $model->updatePhoto();
                }
                $model->save(false);
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Post model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Post the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Post::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }



/**
     * Increments the like count for a specific Post model.
     * @param int $id ID of the Post
     * @return array Response data
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionLike($id)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $post = $this->findModel($id);

        if ($post) {
            $post->like_count += 1;
            $post->save(false);
            return ['success' => true, 'like_count' => $post->like_count];
        }

        return ['success' => false];
    }

    /**
     * Increments the dislike count for a specific Post model.
     * @param int $id ID of the Post
     * @return array Response data
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDislike($id)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $post = $this->findModel($id);

        if ($post) {
            $post->dislike_count += 1;
            $post->save(false);
            return ['success' => true, 'dislike_count' => $post->dislike_count];
        }

        return ['success' => false];
    }
    public function actionIncrementView($id)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        $post = Post::findOne($id);
        if ($post) {
            $post->views++;
            if ($post->save()) {
                return ['success' => true, 'views' => $post->views];
            }
        }
        return ['success' => false];
    }

}

backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use common\models\LoginForm;
use common\models\Post;
use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => \yii\web\ErrorAction::class,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string|Response
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'blank';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
    public function actionExchangeRates()
    {
        $currencyExchange = Yii::$app->currencyExchange;
        $rates = $currencyExchange->getExchangeRates('USD'); // Asosiy valyuta USD bo'lsin

        return $this->render('exchange-rates', [
            'rates' => $rates,
        ]);
    }
    public function actionIncrementView($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $post = Post::findOne($id);
        if ($post) {
            $post->updateCounters(['views' => 1]);
            return ['success' => true, 'views' => $post->views];
        }

        return ['success' => false];
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\LoginForm;
use frontend\models\ContactForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\VerifyEmailForm;
use InvalidArgumentException;
use Yii;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use common\models\Post;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => \yii\web\ErrorAction::class,
            ],
            'captcha' => [
                'class' => \yii\captcha\CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex(int|null $tag_id = null)
    {
        $model = new Post();
        if ($tag_id === null) {
            $data = Post::find()->where(['status' => 1]);
        } else {
            $data = Post::find()->where(['status' => 1, 'tag_id' => $tag_id]);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $data,
            'pagination' => [
                'pageSize' => 10,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                ]
            ],
        ]);

        // API ma'lumotlarini olish
        $apiUrl = 'https://nbu.uz/uz/exchange-rates/json/';
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $apiUrl);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        $response = curl_exec($curl);
        curl_close($curl);
        $rates = json_decode($response, true);

        // Ma'lumotlarni view-ga uzatish
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => $model,
            'rates' => $rates,
        ]);
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }
            return $this->refresh();
        }

        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }

            Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');
            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if (($user = $model->verifyEmail()) && Yii::$app->user->login($user)) {
            Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
            return $this->goHome();
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }

    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
    }

    public function actionExample()
    {
        $content = Yii::$app->request->post('post');
        $cleanedContent = strip_tags($content ?? '');
    }

    public function actionDetail($id)
    {
        $model = Post::findOne($id);
        if (!$model) {
            throw new \yii\web\NotFoundHttpException('The requested page does not exist.');
        }

        $latestPosts = Post::find()->orderBy(['created_at' => SORT_DESC])->limit(5)->all();

        return $this->render('detail', [
            'model' => $model,
            'latestPosts' => $latestPosts,
        ]);
    }


    public function actionSearch()
    {
        $query = Yii::$app->request->get('query');
        $results = [];

        if (!empty($query)) {
            // Perform the search using the query on both 'title' and 'description' columns
            $results = Post::find()
                ->where(['like', 'title', $query])
                ->orWhere(['like', 'description', $query])
                ->all();
        }

        return $this->render('search', [
            'query' => $query,
            'results' => $results,
        ]);
    }
    public function actionIncrementView($id)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $model = $this->findModel($id);
        if ($model) {
            $model->updateCounters(['views' => 1]);
            return ['success' => true, 'views' => $model->views];
        }
        return ['success' => false];
    }


}

frontend/views/site/_post.php
<?php
/* @var $model common\models\Post */

use common\models\Tag;
use yii\bootstrap5\Html;
use yii\helpers\Url;

$tags = Tag::listTags();
?>

<section id="article-list">
    <a href="<?= Url::to(['/site/detail', 'id' => $model->id]) ?>" class="news-card sec-padding ar-item">
        <div class="news-card__img">
            <img src="<?= $model->getPhotoSrc() ?>" alt="Image"/>
        </div>

        <div class="news-card__info">
            <div class="m-title mb-15"><?= Html::encode($model->title) ?></div>
            <div class="m-text mb-15"><?= Html::decode($model->description) ?></div>
            <div class="news-card__bottom">
                <div class="news-card__type wl-ct-name">
                    <?php
                    $tag = Tag::findOne($model->tag_id);
                    if ($tag) {
                        echo Html::encode($tag->name);
                    } else {
                        echo 'Unknown Tag';
                    }
                    ?>
                </div>
                <div class="news-card__date">
                    <img src="https://cdn0.iconfinder.com/data/icons/set-ui-app-android/32/9-512.png" alt="Clock Icon"/>
                    <span><?= Yii::$app->formatter->asRelativeTime($model->updated_at) ?></span>
                </div>
            </div>
            <div class="post-view">
                <p id="view-count">Ko'rilganlar soni: <?= $model->views ?></p>
            </div>
        </div>
    </a>
</section>

<?php
$incrementViewUrl = Url::to(['post/increment-view', 'id' => $model->id]);

$this->registerJs(<<<JS
setTimeout(function() {
    $.ajax({
        url: '$incrementViewUrl',
        method: 'POST',
        success: function(data) {
            if (data.success) {
                $('#view-count').text('Ko\'rilganlar soni: ' + data.views);
            }
        }
    });
}, 10000); // 10 seconds (10000 milliseconds) delay
JS);
?>

frontend/views/site/about.php
 <div class="row">
    <div class="col-xl-9">
        <?= $this->render('exchange-rates' ) ?>
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4 col-xl-3">
            <div class="sec-padding">
                <div class="m-title">Tavsiya etamiz</div>
                <a href="/"
                   class="fast-news sec-mini">
                    <div class="fast-news__img"><img
                                src="https://fivm.giglink.uz/source/thumbnails/_md/1/A3Meu2vB9e2ExaF8RTMWOfxpheW6_FKM_md.jpg">
                    </div>
                    <div class="fast-news__info">Apple yangi katta yangilikka muhtoj: Tim Kukda gʻoyalar
                        tugab qolgan
                    </div>
                </a>

            </div>
        <div class="sticky-el sec-padding">
            <div class="help-section">
                <ul class="help-section__list">
                    <li><a href="/" class="help-section__link">Loyiha haqida</a></li>
                </ul>
                <div class="help-section__description">© 2023 giglink.uz</div>
            </div>
            <ul class="social-mini">
                <li><a href="https://www.facebook.com" target="_blank"
                       class="social-mini__link facebook">
                        <svg width="12" height="23" viewBox="0 0 12 23" fill="none"
                             xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M11.5481 0.555275L8.66986 0.550781C5.43624 0.550781 3.34653 2.63723 3.34653 5.86657V8.3175H0.452578C0.202505 8.3175 0 8.5148 0 8.75817V12.3093C0 12.5527 0.202736 12.7497 0.452578 12.7497H3.34653V21.7103C3.34653 21.9537 3.54904 22.1508 3.79911 22.1508H7.5749C7.82497 22.1508 8.02748 21.9535 8.02748 21.7103V12.7497H11.4112C11.6613 12.7497 11.8638 12.5527 11.8638 12.3093L11.8652 8.75817C11.8652 8.64131 11.8174 8.52941 11.7326 8.44671C11.6479 8.36402 11.5324 8.3175 11.4123 8.3175H8.02748V6.23982C8.02748 5.2412 8.27201 4.73425 9.60873 4.73425L11.5477 4.73357C11.7975 4.73357 12 4.53627 12 4.29314V0.995711C12 0.752797 11.7977 0.555725 11.5481 0.555275Z"
                                  fill="#bababa"/>
                        </svg>
                    </a></li>
                <li><a href="https://t.me" target="_blank"
                       class="social-mini__link telegram">
                        <svg width="24" height="21" viewBox="0 0 24 21" fill="none"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M22.359 0.479006C20.7653 1.06494 1.10121 8.6165 0.810583 8.75713C-0.150355 9.21182 -0.262855 9.81182 0.538708 10.2196C0.618395 10.2618 1.94496 10.6837 3.49652 11.1665L6.31371 12.0431L12.7075 8.03994C16.2278 5.8415 19.1762 4.01338 19.2606 3.98525C19.4809 3.91025 19.6684 3.91494 19.7528 4.004C19.8137 4.06494 19.8184 4.09307 19.7668 4.18213C19.7387 4.24307 17.3996 6.3665 14.5778 8.89775C11.7559 11.4337 9.43558 13.5243 9.42621 13.5478C9.41683 13.5712 9.32308 14.8368 9.21527 16.3603L9.0184 19.1259L9.23402 19.0978C9.35121 19.0837 9.53402 19.0228 9.64183 18.9618C9.75433 18.9056 10.4856 18.2399 11.2778 17.4853C12.0653 16.7306 12.7403 16.0978 12.7731 16.0884C12.8059 16.0743 14.0621 16.9649 15.5668 18.0665C17.0668 19.1681 18.4121 20.1196 18.5575 20.1853C18.9371 20.3634 19.359 20.3774 19.6356 20.2321C19.884 20.1009 20.1231 19.7728 20.2262 19.4306C20.2637 19.2993 21.1262 15.329 22.134 10.6087C23.8168 2.75244 23.9715 1.99307 23.9715 1.58525C23.9715 1.20088 23.9575 1.10713 23.8543 0.905567C23.784 0.760256 23.6575 0.614943 23.5356 0.530567C23.259 0.338381 22.7996 0.314943 22.359 0.479006Z"
                                  fill="#BABABA"/>
                        </svg>
                    </a></li>
                <li><a href="https://twitter.com    " target="_blank"
                       class="social-mini__link twitter">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="256"
                             height="256" viewBox="0 0 256 256" xml:space="preserve">
                                                <g style="stroke:none;stroke-width:0;stroke-dasharray:none;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:10;fill:none;fill-rule:nonzero;opacity:1"
                                                   transform="translate(1.4065934065934016 1.4065934065934016) scale(2.81 2.81)">
                                                    <path d="M 28.303 81.565 c 33.962 0 52.538 -28.138 52.538 -52.538 c 0 -0.799 0 -1.595 -0.054 -2.387 c 3.614 -2.614 6.733 -5.85 9.212 -9.558 c -3.37 1.493 -6.945 2.473 -10.606 2.905 c 3.855 -2.308 6.74 -5.937 8.118 -10.213 c -3.625 2.151 -7.59 3.667 -11.725 4.482 c -6.993 -7.436 -18.69 -7.795 -26.126 -0.802 c -4.796 4.51 -6.83 11.23 -5.342 17.643 C 29.473 30.352 15.64 23.34 6.264 11.804 c -4.901 8.437 -2.398 19.231 5.717 24.649 c -2.939 -0.087 -5.813 -0.88 -8.381 -2.311 c 0 0.076 0 0.155 0 0.234 c 0.002 8.79 6.198 16.36 14.814 18.101 c -2.718 0.741 -5.571 0.85 -8.338 0.317 c 2.419 7.522 9.351 12.675 17.251 12.823 c -6.539 5.139 -14.616 7.928 -22.932 7.92 C 2.926 73.534 1.459 73.445 0 73.27 c 8.444 5.419 18.27 8.293 28.303 8.28"
                                                          style="stroke:none;stroke-width:1;stroke-dasharray:none;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:10;fill-rule:nonzero;opacity:1"
                                                          transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"
                                                          fill="#BABABA"/>
                                                </g>
                                            </svg>
                    </a></li>
            </ul>
        </div>
    </div>
</div>

frontend/views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */
/** @var \frontend\models\ContactForm $model */

use yii\bootstrap5\Html;
use yii\bootstrap5\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::class, [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $exception \yii\web\HttpException */

$this->title = 'Sahifa topilmadi';
?>

<style>
    body {
        background: url('/path/to/your/image.jpg') no-repeat center center fixed;
        background-size: cover;
        color: #fff;
        font-family: Arial, sans-serif;
        text-align: center;
        padding: 10% 0;
    }

    .error-container {
        background: rgba(0, 0, 0, 0.6);
        padding: 20px;
        border-radius: 10px;
        display: inline-block;
        max-width: 600px;
        margin: auto;
    }

    .error-container h1 {
        font-size: 100px;
        margin: 0;
    }

    .error-container p {
        font-size: 20px;
    }

    .error-container a {
        color: #fff;
        text-decoration: underline;
    }
</style>

<div class="error-container">
    <h1>404</h1>

    <p>
        <?= nl2br(Html::encode($exception->getMessage())) ?>
    </p>
    <p>
        <a href="<?= Yii::$app->homeUrl ?>">Bosh sahifaga qaytish</a>
    </p>
</div>

frontend/views/site/search.php
<?php
// frontend/views/site/search.php

/** @var yii\web\View $this */
/** @var string $query */
/** @var array $results */

use common\models\Tag;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Qidirilgan  : ' . Html::encode($query);
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-search">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (empty($results)): ?>
        <p>Bunga tegishli hechnima topilmadi : <strong><?= Html::encode($query) ?></strong>.</p>
    <?php else: ?>
        <ul>
            <?php foreach ($results as $result): ?>
                <li>


                    <div class="page-content">

                        <div class="site-wrapper">
                            <div class="container">
                                <div class="sec-padding">

                                    <div class="row">
                                        <div class="col-12 col-sm-12 col-md-12 col-xl-9">
                                            <section id="article-list">
                                                <a href="<?= Url::to(['/site/detail', 'id' => $result->id]) ?>" class="news-card sec-padding ar-item">
                                                    <div class="news-card__img">
                                                        <img src="<?= $result->getPhotoSrc() ?>" alt="/"/>
                                                    </div>

                                                    <div class="news-card__info">
                                                        <div class="m-title mb-15"><?= Html::encode($result->title) ?></div>
                                                        <div class="m-text mb-15"><?= Html::decode($result->description) ?></div>
                                                        <div class="news-card__bottom">
                                                            <div class="news-card__type wl-ct-name">
                                                                <?php
                                                                $tag = Tag::findOne($result->tag_id);
                                                                if ($tag) {
                                                                    echo Html::encode($tag->name);
                                                                } else {
                                                                    echo 'Noma\'lum Tag';
                                                                }
                                                                ?>
                                                            </div>
                                                            <div class="news-card__date">
                                                                <img src="https://cdn0.iconfinder.com/data/icons/set-ui-app-android/32/9-512.png"/>
                                                                <span> <?= Yii::$app->formatter->asRelativeTime($result->updated_at) ?></span>
                                                            </div>
                                                        </div>


                                                    </div>

                                                </a>
                                            </section>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>